# Generated by Django 4.1.3 on 2022-11-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_organizationworktime_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationworktime',
            old_name='Organization',
            new_name='organization',
        ),
    ]
