# Generated by Django 4.1.3 on 2022-11-30 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_organization_organizationworktime_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userworktime', to=settings.AUTH_USER_MODEL),
        ),
    ]
